---
- name: Table connection to AAP for setup
  hosts: localhost
  gather_facts: false
  connection: local

  pre_tasks:
    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: controller_configs
        extensions: ["yml"]

  roles:
    - {role: infra.controller_configuration.organizations, when: controller_organizations is defined}
    - {role: infra.controller_configuration.teams, when: controller_teams is defined}
    - {role: infra.controller_configuration.users, when: controller_user_accounts is defined}
    - {role: infra.controller_configuration.inventories, when: controller_inventories is defined}
    - {role: infra.controller_configuration.hosts, when: controller_hosts is defined}
